name: Compile Sketch

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  # Manual trigger
  workflow_dispatch:

jobs:
  coding-style:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install eclint
        run: |
          npm install -g eclint

      - name: Check coding style
        run: |
          eclint check $(sh .eclint-files.sh)

  compile-sketch:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:nano:cpu=atmega328'
          libraries: |
            - name: MAX6675 library
            - name: Easy Nextion Library
            - name: TimerInterrupt_Generic
            - name: ADS1X15
            - source-url: https://github.com/banoz/PSM.Library/archive/refs/heads/main.zip
            - source-url: https://github.com/banoz/HX711/archive/refs/heads/master.zip
          sketch-paths: |
            - 'src/gaggiuino.ino'
            - 'scales-calibration/scales-calibration.ino'
